server:
  port: 9092

spring:
  application:
    name: EMPLOYEE-SERVICE
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      localhost:

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE